[package]
name = "advent-of-code-2019-01"
version = "0.1.0"
authors = ["Klaus Ondrag"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
cached = "0.11.0"
timeit = "0.1.2"
